### ISSUE TITLE
Status showing as "Unavailable"

### ISSUE THREAD

**Issue by esigler** [jimmycuadra/lita-hipchat#21]
Starting a few days ago, our Lita instance shows as "Unavailable" in the Hipchat OSX client, and "Available" in the Hipchat web client.

Hubot's Hipchat connector seems to be experiencing the same issue: https://github.com/hipchat/hubot-hipchat/issues/220

This seems likely to be an issue on Hipchat's side, but opening an issue here to track it just in case the client needs to be updated.

For reference, in debug mode, the following line is output when starting Lita up, without an subsequent warnings/errors:

```
DEBUG: Sending initial XMPP presence
```

**Comment by xeraseth** [comment]
I'm having the same problem, though all functionality is working, it just appears as unavailable.

**Comment by jimmycuadra** [comment]
Thanks for the report. I'll watch that other issue and see if there's anything we can do on our end to fix it.

**Comment by jimmycuadra** [comment]
The linked issue confirms it as an issue with the Mac client.
